- id: register-asana-commits
  name: Register Git Commits in Asana
  description: Registers git commits in associated Asana tasks by adding comments
  entry: asana_git_hook.py
  language: python
  language_version: python3
  stages: [post-commit]
  always_run: true
  pass_filenames: false
  require_serial: true
  additional_dependencies: ["requests>=2.25.0"]
